name: Check Copilot Instructions Presence

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verify-instructions:
    name: Verify `.github/copilot-instructions.md` exists and is not empty
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure copilot instructions file exists
        run: |
          FILE=.github/copilot-instructions.md
          echo "Checking $FILE"
          if [ ! -f "$FILE" ]; then
            echo "ERROR: $FILE not found in the PR branch." >&2
            exit 1
          fi
          if [ ! -s "$FILE" ]; then
            echo "ERROR: $FILE is empty." >&2
            exit 1
          fi
          # Optional: check for a required header phrase to ensure this is the expected policy file
          if ! grep -q "Vooraf melden wat je wilt gaan aan passen" "$FILE"; then
            echo "WARNING: $FILE does not contain expected header. Continuing but please review." >&2
          fi
          echo "--- BEGIN $FILE ---"
          sed -n '1,200p' "$FILE" || true
          echo "--- END $FILE ---"
